# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 07:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20170927_0817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='approved_by_management',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='approved_by_supervisor',
        ),
    ]
