# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20170929_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='status',
            field=models.CharField(choices=[('1', 'Approved'), ('2', 'Cancel')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leave',
            name='status_reason',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
