# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_auto_20170929_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(choices=[('0', 'Waiting for approval'), ('1', 'Approved'), ('2', 'Cancel')], default='0', max_length=25),
        ),
        migrations.AlterField(
            model_name='leave',
            name='status_reason',
            field=models.TextField(blank=True),
        ),
    ]
