# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_auto_20170929_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(choices=[('0', 'Waiting for approval'), ('1', 'Approved'), ('2', 'Cancel'), ('3', 'A1'), ('4', 'A2'), ('5', 'A3'), ('6', 'A4'), ('7', 'A5')], default='0', max_length=25),
        ),
    ]
