# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_auto_20171003_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='type',
            field=models.CharField(choices=[('1', 'Casual'), ('2', 'Optional')], max_length=10),
        ),
    ]
