# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_leavebank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavebank',
            name='leave_bank',
            field=models.FloatField(default=0),
        ),
    ]
