# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0016_auto_20171006_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='status',
        ),
        migrations.AddField(
            model_name='leave',
            name='management_approval',
            field=models.CharField(choices=[('0', 'Waiting for approval'), ('1', 'Approved'), ('2', 'Reject')], default='0', max_length=25),
        ),
        migrations.AddField(
            model_name='leave',
            name='supervisor_approval',
            field=models.CharField(choices=[('0', 'Waiting for approval'), ('1', 'Approved'), ('2', 'Reject')], default='0', max_length=25),
        ),
        migrations.AlterField(
            model_name='leave',
            name='reject_type',
            field=models.CharField(blank=True, choices=[('1', 'A1'), ('2', 'A2'), ('3', 'A3')], default=1, max_length=10, null=True),
        ),
    ]
