# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0017_auto_20171009_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='management_approval',
            field=models.CharField(choices=[('0', 'Waiting for management approval'), ('1', 'Approved'), ('2', 'Reject')], default='0', max_length=25),
        ),
        migrations.AlterField(
            model_name='leave',
            name='supervisor_approval',
            field=models.CharField(choices=[('0', 'Waiting for supervisor approval'), ('1', 'Approved'), ('2', 'Reject')], default='0', max_length=25),
        ),
    ]
