# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0018_auto_20171009_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='reject_type',
            field=models.CharField(blank=True, choices=[('2', 'A2'), ('3', 'A3')], max_length=10, null=True),
        ),
    ]
