# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-04 10:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0021_auto_20171103_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavebank',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='leavebank',
            name='modified_by',
        ),
        migrations.AddField(
            model_name='leavebank',
            name='type',
            field=models.CharField(choices=[(b'1', b'added'), (b'2', b'Used agains leave')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leavebank',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_banks', to=settings.AUTH_USER_MODEL),
        ),
    ]
