# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-04 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0022_auto_20171104_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavebank',
            name='type',
            field=models.CharField(choices=[(b'1', b'added'), (b'2', b'Used agains leave')], default=1, max_length=10),
        ),
    ]
