# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-04 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0023_auto_20171104_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavebank',
            name='leave_bank',
            field=models.FloatField(default=1),
        ),
    ]
