# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-04 12:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0024_auto_20171104_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavebank',
            name='created_by',
        ),
    ]
