# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-02-09 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0028_auto_20181230_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeshift',
            name='shift_type',
            field=models.IntegerField(choices=[(9, b'9 Hours'), (10, b'10 Hours')], default=9),
        ),
    ]
