# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-01 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0029_employeeshift_shift_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_from', models.TimeField(verbose_name=b'Start time')),
                ('time_to', models.TimeField(verbose_name=b'End time')),
                ('shift_type', models.IntegerField(choices=[(9, b'9 Hours'), (10, b'10 Hours')], default=9)),
                ('weekOff', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='employeeshift',
            name='shift_type',
        ),
        migrations.RemoveField(
            model_name='employeeshift',
            name='time_from',
        ),
        migrations.RemoveField(
            model_name='employeeshift',
            name='time_to',
        ),
        migrations.AddField(
            model_name='employeeshift',
            name='shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='attendance.Shift'),
        ),
    ]
