# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-01 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0030_auto_20190301_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
