# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-05 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0031_shift_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='weekOff',
        ),
        migrations.AddField(
            model_name='shift',
            name='weekday',
            field=models.IntegerField(blank=True, choices=[(5, b'5 Days'), (6, b'6 Days')], null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='shift_type',
            field=models.IntegerField(choices=[(9, b'9 Hours'), (10, b'10 Hours'), (0, b'Weekly off')], default=9),
        ),
        migrations.AlterField(
            model_name='shift',
            name='time_from',
            field=models.TimeField(blank=True, null=True, verbose_name=b'Start time'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='time_to',
            field=models.TimeField(blank=True, null=True, verbose_name=b'End time'),
        ),
    ]
