# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-01 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0032_auto_20190305_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancemachinelog',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
