# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-05 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0034_userattendancelog_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='userattendancelogsummary',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
