# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-07-04 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0036_auto_20190415_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='reject_type',
            field=models.CharField(blank=True, choices=[(b'1', b'A1'), (b'2', b'A2'), (b'3', b'A3')], max_length=10, null=True),
        ),
    ]
