# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-08-28 18:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0037_auto_20190704_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='time',
            field=models.TimeField(blank=True, choices=[(datetime.time(12, 0), b'12:00 PM'), (datetime.time(12, 30), b'12:30 PM'), (datetime.time(13, 0), b'13:00 PM'), (datetime.time(13, 30), b'13:30 PM'), (datetime.time(14, 0), b'14:00 PM'), (datetime.time(14, 30), b'14:30 PM'), (datetime.time(15, 0), b'15:00 PM'), (datetime.time(15, 30), b'15:30 PM'), (datetime.time(16, 0), b'16:00 PM'), (datetime.time(16, 30), b'16:30 PM'), (datetime.time(17, 0), b'17:00 PM'), (datetime.time(17, 30), b'17:30 PM'), (datetime.time(18, 0), b'18:00 PM'), (datetime.time(18, 30), b'18:30 PM'), (datetime.time(19, 0), b'19:00 PM'), (datetime.time(19, 30), b'19:30 PM'), (datetime.time(20, 0), b'20:00 PM'), (datetime.time(20, 30), b'20:30 PM'), (datetime.time(21, 0), b'21:00 PM'), (datetime.time(21, 30), b'21:30 PM')], max_length=10, null=True),
        ),
    ]
