# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-03-16 11:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0038_auto_20190828_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkFromHome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[(b'1', b'pending'), (b'2', b'Acepted')], default=b'1', max_length=10)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manage_wfh', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wfh', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
