# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-12-01 00:39
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0040_auto_20200317_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidays',
            name='type',
            field=models.CharField(choices=[('1', 'Holiday'), ('2', 'WeekOff'), ('3', 'Optional')], max_length=10),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_for',
            field=models.CharField(choices=[('8', 'Full Day(9 hrs)'), ('6.5', '3/4 day (6 hrs 45 min)'), ('5', '1/2 day (4 hrs 30 min)'), ('2.5', '1/4 day (2 hrs 15 min)'), ('1', '1 Hour')], default='8', max_length=10),
        ),
        migrations.AlterField(
            model_name='leave',
            name='reject_type',
            field=models.CharField(blank=True, choices=[('1', 'A1'), ('2', 'A2'), ('3', 'A3')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='time',
            field=models.TimeField(blank=True, choices=[(datetime.time(12, 0), '12:00 PM'), (datetime.time(12, 30), '12:30 PM'), (datetime.time(13, 0), '13:00 PM'), (datetime.time(13, 30), '13:30 PM'), (datetime.time(14, 0), '14:00 PM'), (datetime.time(14, 30), '14:30 PM'), (datetime.time(15, 0), '15:00 PM'), (datetime.time(15, 30), '15:30 PM'), (datetime.time(16, 0), '16:00 PM'), (datetime.time(16, 30), '16:30 PM'), (datetime.time(17, 0), '17:00 PM'), (datetime.time(17, 30), '17:30 PM'), (datetime.time(18, 0), '18:00 PM'), (datetime.time(18, 30), '18:30 PM'), (datetime.time(19, 0), '19:00 PM'), (datetime.time(19, 30), '19:30 PM'), (datetime.time(20, 0), '20:00 PM'), (datetime.time(20, 30), '20:30 PM'), (datetime.time(21, 0), '21:00 PM'), (datetime.time(21, 30), '21:30 PM')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='type',
            field=models.CharField(choices=[('1', 'Casual Leave'), ('3', 'Emergency Leave'), ('2', 'Optional')], max_length=10),
        ),
        migrations.AlterField(
            model_name='leavebank',
            name='type',
            field=models.CharField(choices=[('1', 'added'), ('2', 'Used agains leave')], default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='shift',
            name='shift_type',
            field=models.IntegerField(choices=[(9, '9 Hours'), (10, '10 Hours'), (0, 'Weekly off')], default=9),
        ),
        migrations.AlterField(
            model_name='shift',
            name='time_from',
            field=models.TimeField(blank=True, null=True, verbose_name='Start time'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='time_to',
            field=models.TimeField(blank=True, null=True, verbose_name='End time'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='weekday',
            field=models.IntegerField(blank=True, choices=[(5, '5 Days'), (6, '6 Days')], null=True),
        ),
        migrations.AlterField(
            model_name='workfromhome',
            name='status',
            field=models.CharField(choices=[('1', 'pending'), ('2', 'Acepted')], default='1', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='workfromhome',
            unique_together=set([('user', 'date')]),
        ),
    ]
