# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-04-01 12:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20190327_1652'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('cover', models.ImageField(upload_to=b'portfolio/')),
                ('estimated_hours', models.IntegerField(blank=True, null=True)),
                ('taken_hours', models.IntegerField(blank=True, null=True)),
                ('client', models.CharField(blank=True, max_length=100, null=True)),
                ('live_url', models.URLField(blank=True, max_length=250, null=True)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('industry', models.ManyToManyField(to='support.Industry')),
                ('skills', models.ManyToManyField(to='user.Skill')),
            ],
        ),
    ]
