# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-12-01 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_auto_20190415_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='cover',
            field=models.ImageField(upload_to='portfolio/'),
        ),
    ]
