# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bond_till',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_of_next_increment',
            field=models.DateField(blank=True, null=True),
        ),
    ]
