# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20170927_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='notice_period',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
