# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-01 10:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_customuser_designation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-full_name']},
        ),
    ]
