# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-30 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20171201_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='designation',
            field=models.CharField(blank=True, choices=[(b'trainee', b'Trainee'), (b'jr_developer', b'Jr. Developer'), (b'developer', b'Developer'), (b'sr_developer', b'Sr. Developer'), (b'atl', b'Asst. Team Lead'), (b'tl', b'Team Lead'), (b'apm', b'Asst Project Manager'), (b'pm', b'Project Manager'), (b'fd', b'Front Desk'), (b'SEO', b'Chief Executive officer'), (b'CTO', b'Chief Technical officer'), (b'BDE', b'Business Development Executive')], max_length=100, null=True),
        ),
    ]
