# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-11 21:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20171230_1113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-first_name']},
        ),
    ]
