# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-29 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20180122_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
