# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-12 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20180807_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(choices=[(b'1', b'Management'), (b'2', b'Development'), (b'3', b'Sales'), (b'4', b'Human Resource'), (b'5', b'Data Entry')], max_length=10),
        ),
    ]
