# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-02-09 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20181012_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(choices=[(b'1', b'Management'), (b'2', b'Development'), (b'3', b'Sales'), (b'4', b'Human Resource'), (b'5', b'Data Entry'), (b'6', b'Creative'), (b'7', b'Digital Marketing')], max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='designation',
            field=models.CharField(blank=True, choices=[(b'trainee', b'Trainee'), (b'jr_developer', b'Jr. Developer'), (b'developer', b'Developer'), (b'sr_developer', b'Sr. Developer'), (b'atl', b'Asst. Team Lead'), (b'tl', b'Team Lead'), (b'apm', b'Asst Project Manager'), (b'pm', b'Project Manager'), (b'fd', b'Front Desk'), (b'hr', b'Hr Manager'), (b'SEO', b'Chief Executive officer'), (b'CTO', b'Chief Technical officer'), (b'BDE', b'Business Development Executive'), (b'seo_executive', b'Seo Executive'), (b'sr_seo_executive', b'Sr seo executive'), (b'jr_seo_executive', b'Jr seo executive'), (b'web_designer', b'Web Designer'), (b'graphic_designer', b'Graphic Designer'), (b'BDM', b'Business Development Manager')], max_length=100, null=True),
        ),
    ]
