# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-27 13:57
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20190209_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='TlFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rating', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10)])),
                ('positive', models.CharField(blank=True, max_length=200, null=True)),
                ('negative', models.CharField(blank=True, max_length=200, null=True)),
                ('suggestion', models.CharField(blank=True, max_length=500, null=True)),
                ('rating_provided', models.BooleanField(default=False)),
                ('tl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tl_feedbacks', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
