# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-27 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_tlfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tlfeedback',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
