# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-27 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20190327_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tlfeedback',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=1),
        ),
    ]
