# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-12-01 12:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20201201_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='date_of_next_increment',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='password_date',
        ),
    ]
