# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-05 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheettype',
            name='type',
            field=models.CharField(choices=[('task', 'Task(Custom)'), ('estimation', 'Estimation'), ('client', 'Client'), ('pro_service', 'Project/service'), ('team', 'Team'), ('inhouse', 'GEITPL-Inhouse'), ('learning', 'Learning/Training')], max_length=100, verbose_name='Timesheet Type'),
        ),
    ]
