# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-08 12:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0003_auto_20180105_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheetfiled',
            name='approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timesheet_approves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timesheetfiled',
            name='approve',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='timesheettype',
            name='field_type',
            field=models.CharField(choices=[('user', 'User Model'), ('service', 'Service Model'), ('clients', 'Clients'), ('text', 'Text filed'), ('m2m_user', 'Many to Many User'), ('m2m_service', 'Many to Many User')], default='text', max_length=100, verbose_name='Timesheet Type'),
        ),
    ]
