# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-11 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20180108_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheettype',
            name='comment',
            field=models.CharField(default='Lower Value is better', max_length=100, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='timesheettype',
            name='percentage',
            field=models.IntegerField(default=100, verbose_name='Performance percenrage of category'),
        ),
    ]
