# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-12 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20180112_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheettype',
            name='css_class',
            field=models.CharField(default='bg-muted', max_length=100, verbose_name='Title'),
        ),
    ]
