# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-03 01:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0006_timesheettype_css_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheetfiled',
            name='approval',
        ),
        migrations.AddField(
            model_name='timesheetfiled',
            name='approver_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timesheet_approver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timesheetfiled',
            name='approve',
            field=models.CharField(choices=[('new', 'New'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=30, verbose_name='Timesheet Status'),
        ),
    ]
