# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-01 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_auto_20190103_0649'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='service.Service'),
        ),
        migrations.AddField(
            model_name='servicerecords',
            name='action',
            field=models.CharField(choices=[('1', 'Added'), ('2', 'Deleted')], default='1', max_length=30, verbose_name='Services Status'),
        ),
    ]
