# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-01 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_auto_20190301_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerecords',
            name='status',
            field=models.CharField(choices=[(b'open', b'Working'), (b'expected', b'Expected to Start'), (b'scheduled', b'Scheduled to Start'), (b'pause', b'paused'), (b'closed', b'closed'), (b'expire', b'expired'), (b'done', b'complted')], default='open', max_length=30, verbose_name='Services Status'),
        ),
    ]
