# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-02 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_auto_20190301_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheetfiled',
            name='date',
            field=models.DateField(null=True, verbose_name='Date'),
        ),
    ]
