# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-06 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_auto_20190302_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.CharField(choices=[('dedicated', 'Dedicated'), ('hourly', 'Hourly Basic'), ('shared', 'Shared'), ('estimation', 'Estimation Basis'), ('freetask', 'Free  Service')], max_length=30, verbose_name='Services Type'),
        ),
    ]
