# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 08:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0002_auto_20170927_0817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='status',
        ),
    ]
