# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0003_remove_lead_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('skype', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='lead',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='email',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='skype',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='email',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='skype',
        ),
    ]
