# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 06:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0006_auto_20171025_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunityscheduler',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sche_client_detail', to='opportunity.Client'),
        ),
    ]
