# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0007_opportunityscheduler_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_client_detail', to='opportunity.Client'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opp_client_detail', to='opportunity.Client'),
        ),
        migrations.AlterField(
            model_name='opportunityscheduler',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sche_client_detail', to='opportunity.Client'),
        ),
    ]
