# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 07:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0008_auto_20171025_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunityscheduler',
            name='client',
        ),
    ]
