# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-29 21:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0009_remove_opportunityscheduler_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='client',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='client',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='client',
            name='modified_by',
        ),
    ]
