# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-02-04 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0010_auto_20171230_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='conatct',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='email',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='looking_for_hire',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='skype',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='technology',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
