# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-02-04 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0013_auto_20190204_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='firstname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='lastname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
