# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-07-04 02:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opportunity', '0014_auto_20190204_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='lead',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='leadscheduler',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='client',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='estimated_price',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='opportunityscheduler',
            name='modified_by',
        ),
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[(b'1', b'New'), (b'2', b'In communication'), (b'3', b'converted to project'), (b'4', b'Not Intrested'), (b'5', b'No Responce'), (b'111', b'Created by Website')], default=b'1', max_length=1),
        ),
        migrations.AddField(
            model_name='lead',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_lead', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='status',
            field=models.CharField(choices=[(b'1', b'New'), (b'2', b'In communication'), (b'3', b'converted to project'), (b'4', b'Not Intrested'), (b'5', b'No Responce'), (b'111', b'Created by Website')], default=b'1', max_length=1),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_opportunity', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leadscheduler',
            name='communication_type',
            field=models.CharField(choices=[(b'1', b'Skype'), (b'2', b'Email'), (b'3', b'Phone Call'), (b'4', b'Linkedin'), (b'5', b'Facebook'), (b'6', b'Whatsapp'), (b'7', b'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='leadscheduler',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_leadscheduler', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leadscheduler',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduler', to='opportunity.Lead'),
        ),
        migrations.AlterField(
            model_name='leadscheduler',
            name='result',
            field=models.CharField(choices=[(b'1', b'New'), (b'3', b'converted to project'), (b'4', b'Not Intrested'), (b'5', b'No Responce'), (b'6', b'New call')], default=b'1', max_length=1),
        ),
        migrations.AlterField(
            model_name='opportunityscheduler',
            name='communication_type',
            field=models.CharField(choices=[(b'1', b'Skype'), (b'2', b'Email'), (b'3', b'Phone Call'), (b'4', b'Linkedin'), (b'5', b'Facebook'), (b'6', b'Whatsapp'), (b'7', b'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='opportunityscheduler',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_opportunityscheduler', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='opportunityscheduler',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduler', to='opportunity.Opportunity'),
        ),
        migrations.AlterField(
            model_name='opportunityscheduler',
            name='result',
            field=models.CharField(choices=[(b'1', b'New'), (b'3', b'converted to project'), (b'4', b'Not Intrested'), (b'5', b'No Responce'), (b'6', b'New call')], default=b'1', max_length=1),
        ),
        migrations.AddField(
            model_name='client',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='opportunity.Country'),
        ),
    ]
