# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-07-04 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0015_auto_20190704_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[(b'1', b'Website'), (b'2', b'Email Marketing'), (b'3', b'Client Reference'), (b'4', b'Linkedin'), (b'5', b'Facebook'), (b'6', b'Whatsapp'), (b'7', b'Clutch'), (b'7', b'Craigslist'), (b'8', b'Other')], default=b'1', max_length=1),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='source',
            field=models.CharField(choices=[(b'1', b'Website'), (b'2', b'Email Marketing'), (b'3', b'Client Reference'), (b'4', b'Linkedin'), (b'5', b'Facebook'), (b'6', b'Whatsapp'), (b'7', b'Clutch'), (b'7', b'Craigslist'), (b'8', b'Other')], default=b'1', max_length=1),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[(b'1', b'New'), (b'2', b'Positive Response'), (b'3', b'Hot Prospect'), (b'4', b'converted to Project'), (b'5', b'Not Intrested'), (b'6', b'No Response'), (b'111', b'Created by Website')], default=b'1', max_length=1),
        ),
        migrations.AlterField(
            model_name='leadscheduler',
            name='communication_type',
            field=models.CharField(choices=[(b'1', b'Skype'), (b'2', b'Drop a Email'), (b'3', b'Phone Call'), (b'4', b'Linkedin'), (b'5', b'Facebook'), (b'6', b'Whatsapp'), (b'7', b'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='leadscheduler',
            name='result',
            field=models.CharField(choices=[(b'1', b'Next call'), (b'4', b'Lose'), (b'5', b'No Response'), (b'6', b'move to to next step')], default=b'1', max_length=1),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='status',
            field=models.CharField(choices=[(b'1', b'New'), (b'2', b'Positive Response'), (b'3', b'Hot Prospect'), (b'4', b'converted to Lead'), (b'5', b'Not Intrested'), (b'6', b'No Response'), (b'111', b'Created by Website')], default=b'1', max_length=1),
        ),
        migrations.AlterField(
            model_name='opportunityscheduler',
            name='communication_type',
            field=models.CharField(choices=[(b'1', b'Skype'), (b'2', b'Drop a Email'), (b'3', b'Phone Call'), (b'4', b'Linkedin'), (b'5', b'Facebook'), (b'6', b'Whatsapp'), (b'7', b'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='opportunityscheduler',
            name='result',
            field=models.CharField(choices=[(b'1', b'Next call'), (b'4', b'Lose'), (b'5', b'No Response'), (b'6', b'move to to next step')], default=b'1', max_length=1),
        ),
    ]
