# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-07-04 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0016_auto_20190704_0301'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='linkedin',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
