# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-07-04 03:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0017_client_linkedin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='lastname',
        ),
        migrations.AddField(
            model_name='client',
            name='client_comapny',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prospects', to='opportunity.Country'),
        ),
    ]
