# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-12-01 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0019_auto_20190828_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('1', 'Website'), ('2', 'Email Marketing'), ('3', 'Client Reference'), ('4', 'Linkedin'), ('5', 'Facebook'), ('6', 'Whatsapp'), ('7', 'Clutch'), ('8', 'Craigslist'), ('9', 'Other')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('1', 'New'), ('2', 'Positive Response'), ('3', 'Hot Prospect'), ('4', 'converted to Project'), ('5', 'Not Intrested'), ('6', 'No Response'), ('111', 'Created by Website')], default='1', max_length=4),
        ),
        migrations.AlterField(
            model_name='leadscheduler',
            name='call_schedule',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Next schedule Date if any'),
        ),
        migrations.AlterField(
            model_name='leadscheduler',
            name='communication_type',
            field=models.CharField(choices=[('1', 'Skype'), ('2', 'Drop a Email'), ('3', 'Phone Call'), ('4', 'Linkedin'), ('5', 'Facebook'), ('6', 'Whatsapp'), ('7', 'Other')], max_length=20, verbose_name='Mediam of communication'),
        ),
        migrations.AlterField(
            model_name='leadscheduler',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Client communication Details'),
        ),
        migrations.AlterField(
            model_name='leadscheduler',
            name='result',
            field=models.CharField(choices=[('0', 'Mark as Lead'), ('1', 'Next call'), ('2', 'Lose'), ('3', 'No Response'), ('4', 'complted')], default='1', max_length=1, verbose_name='Result of Last call'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='description',
            field=models.TextField(blank=True, help_text='its can be project or client detail', null=True, verbose_name='Project Details'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='source',
            field=models.CharField(choices=[('1', 'Website'), ('2', 'Email Marketing'), ('3', 'Client Reference'), ('4', 'Linkedin'), ('5', 'Facebook'), ('6', 'Whatsapp'), ('7', 'Clutch'), ('8', 'Craigslist'), ('9', 'Other')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='status',
            field=models.CharField(choices=[('1', 'New'), ('2', 'Positive Response'), ('3', 'Hot Prospect'), ('4', 'converted to Lead'), ('5', 'Not Intrested'), ('6', 'No Response'), ('111', 'Created by Website')], default='1', max_length=4),
        ),
        migrations.AlterField(
            model_name='opportunityscheduler',
            name='call_schedule',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Next schedule Date if any'),
        ),
        migrations.AlterField(
            model_name='opportunityscheduler',
            name='communication_type',
            field=models.CharField(choices=[('1', 'Skype'), ('2', 'Drop a Email'), ('3', 'Phone Call'), ('4', 'Linkedin'), ('5', 'Facebook'), ('6', 'Whatsapp'), ('7', 'Other')], max_length=20, verbose_name='Mediam of communication'),
        ),
        migrations.AlterField(
            model_name='opportunityscheduler',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Client communication Details'),
        ),
        migrations.AlterField(
            model_name='opportunityscheduler',
            name='result',
            field=models.CharField(choices=[('0', 'Mark as Lead'), ('1', 'Next call'), ('2', 'Lose'), ('3', 'No Response'), ('4', 'complted')], default='1', max_length=1, verbose_name='Result of Last call'),
        ),
    ]
