# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-12-01 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(verbose_name='Start Date')),
                ('end', models.DateField(verbose_name='end Date')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('is_open', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('year', models.IntegerField(unique=True, verbose_name='Year Name')),
                ('is_open', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='fiscalyear',
            unique_together=set([('start', 'end')]),
        ),
    ]
