"""
Django settings for geitpl_erp project.

Generated by 'django-admin startproject' using Django 1.11.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os, sys
from unipath import Path
from django.conf.global_settings import DATETIME_INPUT_FORMATS

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
PROJECT_DIR = Path(__file__).ancestor(3)
PROJECT_APPS = Path(__file__).ancestor(2)

sys.path.insert(0, Path(PROJECT_APPS, 'apps'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'p=x!zoj9e%yfv$z)$8qh1eutu29oa=c9&dl6v^_wv$*i(ba2u2'
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'widget_tweaks',
    'sorl.thumbnail',
    'config',
    'user',
    'department',
    'opportunity',
    'attachment',
    'dashboard',
    'estimation',
    'attendance',
    'django_celery_results',
    'contract',
    'support',
    'service'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'user.middleware.LoginMiddleware',
]

ROOT_URLCONF = 'geitpl_erp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [PROJECT_APPS.child("templates"),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'geitpl_erp.wsgi.application'

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = False


MEDIA_ROOT = os.path.join(os.path.join(PROJECT_DIR, 'geitpl_erp'), "media")
MEDIA_URL = '/media/'
STATIC_ROOT = PROJECT_DIR.child("collected_static")
STATIC_URL = '/static/'

STATICFILES_DIRS = (
    os.path.join(os.path.join(PROJECT_DIR, 'geitpl_erp'), "static"),
)

AUTH_PROFILE_MODULE = "user.CustomUser"
AUTH_USER_MODEL = "user.CustomUser"

DATE_INPUT_FORMATS = ['%m-%d-%Y']
TIME_INPUT_FORMATS = ['%I:%M%p', '%I:%M %p']
DATETIME_INPUT_FORMATS += ('%m-%d-%Y %I:%M %p',)


from django.core.urlresolvers import reverse_lazy
LOGIN_URL = reverse_lazy('user:login')

LOGIN_REQUIRED_URLS = (
    r'/employee/(.*)$',
    r'/common/(.*)$',
    r'/administration/(.*)$',
)

LOGIN_REQUIRED_URLS_EXCEPTIONS = (
    r'/$',
    r'/user(.*)$',
    r'/ajax/(.*)$',
    r'/support/(.*)$',
    r'/search/(.*)$',
    r'/admin/(.*)$',
)

#celery settings
CELERY_RESULT_BACKEND = 'django-db'
CELERY_TASK_ALWAYS_EAGER = True
CELERY_BROKER_URL = 'amqp://guest:guest@localhost:5672//'
CELERY_TASK_SERIALIZER = "json"  
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_RESULT_SERIALIZER = "json"


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.zoho.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "info@geitpl.com"
EMAIL_HOST_PASSWORD = "Geitpl@#$123"