# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 14:04
from __future__ import unicode_literals

import contract.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractComponant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('method', models.CharField(choices=[(b'formula', b'Formula'), (b'fixed', b'Fixed'), (b'percentage', b'Percentage')], max_length=100)),
                ('condition', models.CharField(default=b'1', max_length=500, verbose_name=b'Condition when this apply')),
                ('type', models.CharField(choices=[(b'BA', b'Basic'), (b'HRA', b'HRA'), (b'DA', b'DA'), (b'PF', b'PF'), (b'ESIC', b'ESIC'), (b'GHI', b'GHI'), (b'TDS', b'TDS'), (b'BO', b'Bonus'), (b'INC', b'Incentive'), (b'TRAI', b'Taining'), (b'DED', b'Deduction'), (b'ALL', b'Allowance')], max_length=100)),
                ('code', models.CharField(choices=[(b'DED', b'Deduction'), (b'BO', b'BONUS'), (b'ALL', b'Allowance')], max_length=100)),
                ('amount', models.CharField(max_length=500, verbose_name=b'Formula / fixed / Percentage')),
            ],
        ),
        migrations.CreateModel(
            name='PaySlip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('leave_in_bank', models.CharField(default=b'0', max_length=5)),
                ('leave_in_month', models.CharField(default=b'0', max_length=5)),
                ('office_working_days', models.CharField(default=b'0', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='PayslipComponant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.FloatField(default=0, verbose_name=b'Amount')),
                ('type', models.CharField(choices=[(b'BA', b'Basic'), (b'HRA', b'HRA'), (b'DA', b'DA'), (b'GHI', b'GHI'), (b'PTAX', b'PTAX'), (b'PF', b'PF'), (b'ESIC', b'ESIC'), (b'TDS', b'TDS'), (b'BO', b'Bonus'), (b'INC', b'Incentive'), (b'TRAI', b'Taining'), (b'DED', b'Deduction'), (b'ALL', b'Allowance')], max_length=50)),
                ('code', models.CharField(choices=[(b'DED', b'Deduction'), (b'BO', b'BONUS'), (b'ALL', b'Allowance')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_slip_lines', to='contract.PaySlip')),
            ],
        ),
        migrations.RemoveField(
            model_name='contract',
            name='basic_salary',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='conveyance_allowance',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='home_allowance',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='medical_insurance',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='professional_tax',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='provident_fund',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='tds',
        ),
        migrations.AddField(
            model_name='contract',
            name='basic',
            field=models.FloatField(default=0, verbose_name=b'Basic Salary'),
        ),
        migrations.AddField(
            model_name='contract',
            name='da',
            field=models.FloatField(default=0, verbose_name=b'DA'),
        ),
        migrations.AddField(
            model_name='contract',
            name='hra',
            field=models.FloatField(default=0, verbose_name=b'HRA'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts_created', to=settings.AUTH_USER_MODEL, verbose_name=b'Created By'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='expiry_date',
            field=models.DateField(default=contract.models.get_next_increment),
        ),
        migrations.AlterField(
            model_name='contract',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts_modified', to=settings.AUTH_USER_MODEL, verbose_name=b'Modified By'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payslip',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.Contract'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips_created', to=settings.AUTH_USER_MODEL, verbose_name=b'Created By'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractcomponant',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componants', to='contract.Contract'),
        ),
    ]
