# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-01 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_auto_20171110_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='total_preset_days',
            field=models.CharField(default=b'0', max_length=5),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='office_working_days',
            field=models.CharField(default=b'0', max_length=5, verbose_name=b'Number of working days in a month'),
        ),
    ]
