# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 05:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_auto_20171201_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_slips', to=settings.AUTH_USER_MODEL),
        ),
    ]
