# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-01 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0005_auto_20171201_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='beneficiary_account_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=b'Account Number'),
        ),
        migrations.AddField(
            model_name='contract',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=b'ifsc code'),
        ),
    ]
