# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-05 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0007_auto_20180104_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='office_working_days',
            field=models.CharField(default=b'0', max_length=5, verbose_name=b'working dayS'),
        ),
    ]
