# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-12-01 00:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0017_auto_20200316_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='basic',
            field=models.FloatField(default=0, verbose_name='Basic Salary'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='beneficiary_account_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Account Number'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='da',
            field=models.FloatField(default=0, verbose_name='DA'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='hra',
            field=models.FloatField(default=0, verbose_name='HRA'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ifsc code'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified By'),
        ),
        migrations.AlterField(
            model_name='contractcomponant',
            name='amount',
            field=models.CharField(max_length=500, verbose_name='Formula / fixed / Percentage'),
        ),
        migrations.AlterField(
            model_name='contractcomponant',
            name='code',
            field=models.CharField(choices=[('DED', 'Deduction'), ('BO', 'BONUS'), ('ALL', 'Allowance')], max_length=100),
        ),
        migrations.AlterField(
            model_name='contractcomponant',
            name='condition',
            field=models.CharField(default='1', max_length=500, verbose_name='Condition when this apply'),
        ),
        migrations.AlterField(
            model_name='contractcomponant',
            name='method',
            field=models.CharField(choices=[('formula', 'Formula'), ('fixed', 'Fixed'), ('percentage', 'Percentage')], max_length=100),
        ),
        migrations.AlterField(
            model_name='contractcomponant',
            name='type',
            field=models.CharField(choices=[('BA', 'Basic'), ('HRA', 'HRA'), ('DA', 'DA'), ('PF', 'PF'), ('ESIC', 'ESIC'), ('GHI', 'GHI'), ('TDS', 'TDS'), ('BO', 'Bonus'), ('INC', 'Incentive'), ('TRAI', 'Taining'), ('DED', 'Deduction'), ('ALL', 'Allowance')], max_length=100),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='leave_in_bank',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='leave_in_month',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='office_working_days',
            field=models.CharField(default='0', max_length=5, verbose_name='working dayS'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='salary_month',
            field=models.CharField(choices=[('january', 'January'), ('feburary', 'Feburary'), ('march', 'March'), ('april', 'April'), ('may', 'May'), ('june', 'June'), ('july', 'July'), ('august', 'August'), ('september', 'September'), ('october', 'October'), ('november', 'November'), ('december', 'December')], default='december', max_length=20),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='total_preset_days',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='payslipcomponant',
            name='amount',
            field=models.FloatField(default=0, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='payslipcomponant',
            name='code',
            field=models.CharField(choices=[('DED', 'Deduction'), ('BO', 'BONUS'), ('ALL', 'Allowance')], max_length=100),
        ),
        migrations.AlterField(
            model_name='payslipcomponant',
            name='type',
            field=models.CharField(choices=[('BA', 'Basic'), ('HRA', 'HRA'), ('DA', 'DA'), ('GHI', 'GHI'), ('PTAX', 'PTAX'), ('PF', 'PF'), ('ESIC', 'ESIC'), ('TDS', 'TDS'), ('BO', 'Bonus'), ('INC', 'Incentive'), ('TRAI', 'Taining'), ('DED', 'Deduction'), ('ALL', 'Allowance')], max_length=50),
        ),
    ]
